"""Экспорт данных для интерактивной карты."""
import pandas as pd
import json
import os

# Prefer full catalog if available, fall back to original
import pathlib
_full = pathlib.Path('data/processed/unified_catalog_full.csv')
_orig = pathlib.Path('results/unified_catalogue.csv')
df = pd.read_csv(str(_full) if _full.exists() else str(_orig))
df = df[df['magnitude'] >= 6.5].copy()

total = len(df)

# Полный каталог для интерактивной карты (file:// не поддерживает fetch)
map_df = df.sort_values('year')

events = []
for _, row in map_df.iterrows():
    # Resolve region column
    region = str(row.get('flinn_engdahl_region', row.get('region', 'Unknown')))
    events.append({
        'lat': round(float(row['lat']), 3),
        'lon': round(float(row['lon']), 3),
        'mag': round(float(row['magnitude']), 1),
        'year': int(row.get('year', 0)),
        'region': region,
        'id': str(row.get('event_id', ''))
    })

# Данные серий (топ-16 мультирегиональных)
series_data = []
try:
    with open('results/clusters.json') as f:
        clusters = json.load(f)
    for i, (sid, sdata) in enumerate(list(clusters.items())[:16]):
        if isinstance(sdata, dict) and 'events' in sdata:
            series_data.append({'id': sid, 'events': sdata['events'][:5]})
except Exception:
    pass

output = {'events': events, 'series': series_data, 'total': total}

os.makedirs('presentation', exist_ok=True)
with open('presentation/map_data.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False)

embed_path = 'presentation/map_events_embed.js'
with open(embed_path, 'w', encoding='utf-8') as f:
    f.write('/* Auto-generated by scripts/export_map_data.py — do not edit */\n')
    f.write('window.MAP_EVENTS = ')
    json.dump(events, f, ensure_ascii=False)
    f.write(';\n')

print(f"Экспортировано {len(events)} событий (из {total} M>=6.5)")
print(f"  -> {embed_path}")
